### ISSUE TITLE
希望修改地图翻译的错误 ze_a_e_s_t_h_e_t_i_c_v1_1

### ISSUE THREAD

**Issue by MunchiesSheng** [fys-csgo/servers-config#1892]
在今天的指挥游玩过程中，我们发现人类团队在飞机位置触发了错误的翻译文本
具体表现为，错误的翻译了后面棋子的解密提示
具体代码为
```kvlang
   "** Has anybody seen the keys that open the window to reach the stars? **"
    {
        "chi" "**快把两枚棋子靠在一起**"
    }
```
在具体console_t对应地图文件的174 - 177行
可以把翻译修改成有人看到打开窗户去接触星星的钥匙吗？

或者是  ```有人发现了在星际中穿梭的钥匙吗？```

**Comment by Kxnrl** [comment]
https://github.com/fys-csgo/servers-config/compare
