### ISSUE TITLE
csgo

### ISSUE THREAD

**Issue by eric007123** [fys-csgo/servers-config#1948]
我的游戏名字get-right，早上8点，游戏玩的好好的csgo，突然有人进来问我在不在，还有什么问题，当时在玩游戏，我也没来得急看，我就在想op找我干什么，我忘记op叫什么名字了，游戏玩的好好的直接给我禁赛了一天，我就正常玩个游戏都禁赛吗，那你这个凤雲社，不让玩家好好玩游戏，正常体验一下，游戏不就是开心快乐的玩，直接代码给我踢了，不让我玩，点名批评8点的op，有个人好像叫他过来，当时也在听歌，op找我的时候我都是懵逼的，没时间理他，               2022/12/4   GET-RiGHT  8点有个op把我禁赛   好好玩个游戏禁我赛       csgo凤雲社区的

**Comment by eric007123** [comment]
凤雲社区，只有关系户吗

**Comment by eric007123** [comment]
玩个游戏喊人过来找我问话，

**Comment by WLLbuou** [comment]
我是早上那名OP，你于地图内多次触发传送剧本，且次数大于等于3次。多次询问你你并未解释原因，且多名玩家开麦提醒你不要触发传送剧本你依旧我行我素不听劝阻，给大量玩家造成了极为糟糕的游戏体验，遂给与1天封禁处理。对于不熟悉的地图请务必戴上耳机游戏，熟读模式规则在进行游戏，对于封禁处理有异议已经OP处理存在包庇以及不合理的处理等行为可前往论坛申述板块发帖进行申诉。
